### ISSUE TITLE
페르소나 대화

### ISSUE THREAD

**Issue by ryugibo** [pal-ette/iNotePal#4]
https://www.aihub.or.kr/aihubdata/data/view.do?currMenu=&topMenu=&aihubDataSe=data&dataSetSn=71302

**Comment by doctorpeppercokebear** [comment]
json 파일이 dictionary, dict) 형식과 Series 형식이 혼합되어 있어서

' Mixing dicts with non-Series may lead to ambiguous ordering.' 같은 오류가 발생한다
